# Generated by Django 6.1 on 2026-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='news/pdfs/'),
        ),
    ]
