# Generated by Django 6.1 on 2026-08-29 18:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('previous', 'Previous')], default='current', max_length=10),
        ),
        migrations.AddField(
            model_name='leader',
            name='year',
            field=models.CharField(blank=True, help_text='e.g. 2015 or 2015-2019. Only used for Previous leaders.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='news_pdfs/'),
        ),
    ]
