# Generated by Django 6.1 on 2026-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leader_status_leader_year_alter_news_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='columns',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_front_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='subheadline',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
