# Generated by Django 6.1 on 2026-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_news_author_news_category_news_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='zoro_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
